# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 295)
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 511, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.firstButton = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.firstButton.setObjectName("firstButton")
        self.verticalLayout.addWidget(self.firstButton)
        self.businessButton = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.businessButton.setObjectName("businessButton")
        self.verticalLayout.addWidget(self.businessButton)
        self.economicButton = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.economicButton.setObjectName("economicButton")
        self.verticalLayout.addWidget(self.economicButton)
        self.resultLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.resultLabel.setText("")
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)
        self.label.raise_()
        self.resultLabel.raise_()
        self.businessButton.raise_()
        self.economicButton.raise_()
        self.firstButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Wybierz klasę lotu:"))
        self.firstButton.setText(_translate("Dialog", "Pierwsza klasa: 200zł"))
        self.businessButton.setText(_translate("Dialog", "Business klasa: 150zł"))
        self.economicButton.setText(_translate("Dialog", "Klasa ekonomiczna: 20zł"))
